extends: airbnb-base
plugins:
  - import
rules:
  no-shadow: off
  import/no-dynamic-require: off
  global-require: off
  no-param-reassign: off
  consistent-return: off
  arrow-body-style: off
  no-underscore-dangle: off
  import/extensions: off
  prefer-destructuring: off
  strict: off
  max-len: off
  no-console: off
globals:
  process: on
  describe: on
  before: on
  after: on
  beforeEach: on
  suite: on
  test: on
  it: on
